{% set name = "helics" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GMLC-TDC/HELICS/releases/download/v{{ version }}/Helics-v{{ version }}-source.tar.gz
  sha256: 4b9a733a568ae8e6492f93abcd43f1aa9c53b233edcbeb0ab188dcc0d73ac928

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - ninja  # [win]
    - swig
  host:
    - boost-cpp
    - python
    - pip
    - zeromq
  run:
    - boost-cpp
    - python
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: https://docs.helics.org/en/latest/
  dev_url: https://github.com/GMLC-TDC/HELICS

extra:
  recipe-maintainers:
    - kdheepak
    - anthchirp
